AWSTemplateFormatVersion: 2010-09-09
Resources:
  PostgresRDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBName: uniquedatabase
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Sub "{{resolve:ssm:masterusername}}"
      MasterUserPassword: !Sub "{{resolve:ssm:masteruserpassword}}"
      AllocatedStorage: "20"
  DBUsername:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Rdsusername
      Type: String
      Value: !Sub "{{resolve:ssm:masterusername}}"
  DBPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Rdspassword
      Type: String
      Value: !Sub "{{resolve:ssm:masteruserpassword}}"
  ReturnValue:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: alinkmaybe
      Type: String
      Value: !Join ['',[jdbc:postgresql://, !GetAtt PostgresRDS.Endpoint.Address, ":", !GetAtt PostgresRDS.Endpoint.Port, "/", !Ref PostgresRDS]]

Outputs:
  DatabaseName:
    Description: Return the database name
    Value: !Ref PostgresRDS
