AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBName:
    Type: String
    Value: uniquedatabase
Resources:
  PostgresRDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBName: !Ref DBName
      DBInstanceClass: db.t2.micro
      Engine: postgres
      MasterUsername: !Sub "{{resolve:ssm:masterusername}}"
      MasterUserPassword: !Sub "{{resolve:ssm:masteruserpassword}}"
      AllocatedStorage: "20"
  DBUsername:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: Rdsusername
      Type: String
      Value: ${{ secrets.DB_USERNAME }}
  DBPassword:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: Rdspassword
      Type: String
      Value: ${{ secrets.DB_PASSWORD }}
  ReturnValue:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: alinkmaybe
      Type: String
      Value: !Join ['',[jdbc:postgresql://, !GetAtt PostgresRDS.Endpoint.Address, ":", !GetAtt PostgresRDS.Endpoint.Port, "/", !Ref PostgresRDS]]
Outputs:
  DatabaseName:
    Value: !Ref PostgresRDS
